version: '3.9'

services:
  autoservice-db:
    container_name: autoservice-db
    image: postgres:alpine
    ports:
      - 5432:5432
    expose:
      - 5432
    env_file:
      - .env
    volumes: 
    - ./db-data/1-generate-db.sql:/docker-entrypoint-initdb.d/1-generate-db.sql
    - ./db-data/2-fill-db.sql:/docker-entrypoint-initdb.d/2-fill-db.sql
    restart: unless-stopped
    networks:
      - auto-net

  frontend:
    container_name: autoservice-frontend
    image: autoservice-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: unless-stopped
    depends_on:
      - autoservice-db
    networks:
      - auto-net

volumes:
  autoservice-db:

networks:
  auto-net:
    driver: bridge