DROP TABLE IF EXISTS Administrator CASCADE;

DROP TABLE IF EXISTS Mechanik CASCADE;

DROP TABLE IF EXISTS Osoba CASCADE;

DROP TABLE IF EXISTS Rezervace CASCADE;

DROP TABLE IF EXISTS Role CASCADE;

DROP TABLE IF EXISTS Sluzba CASCADE;

DROP TABLE IF EXISTS Vozidlo CASCADE;

DROP TABLE IF EXISTS Zakaznik CASCADE;


CREATE TABLE Administrator
(
	BankovniUcet VARCHAR(50) NOT NULL ,
	Plat DOUBLE PRECISION NOT NULL,
	AdministratorID INT NOT NULL GENERATED ALWAYS AS IDENTITY,
	CONSTRAINT PK_Administrator PRIMARY KEY (AdministratorID)
);

CREATE TABLE Mechanik
(
	BankovniUcet VARCHAR(50) NOT NULL ,
	Plat DOUBLE PRECISION NOT NULL,
	Specializace VARCHAR(50) NOT NULL,
	MechanikID INT CHECK (MechanikID > 0) NOT NULL GENERATED ALWAYS AS IDENTITY,
	CONSTRAINT PK_Mechanik PRIMARY KEY (MechanikID)
);

CREATE TABLE Osoba
(
	Email VARCHAR(50) NOT NULL,
	Jmeno VARCHAR(50) NOT NULL,
	Prijmeni VARCHAR(50) NOT NULL,
	TelCislo VARCHAR(50) NOT NULL,
	OsobaID INT NOT NULL GENERATED ALWAYS AS IDENTITY,
	CONSTRAINT PK_Osoba PRIMARY KEY (OsobaID)
);

CREATE TABLE Rezervace
(
	Cas TIME(0) NOT NULL,
	Cena DOUBLE PRECISION NOT NULL,
	Datum DATE NOT NULL,
	RezervaceID INT NOT NULL GENERATED ALWAYS AS IDENTITY,
	MechanikID INT NULL,
	VozidloID INT NOT NULL,
	CONSTRAINT PK_Rezervace PRIMARY KEY (RezervaceID)
);

CREATE TABLE Role
(
	RoleID INT NOT NULL GENERATED ALWAYS AS IDENTITY,
	OsobaID INT NOT NULL,
	CONSTRAINT PK_Role PRIMARY KEY (RoleID)
);

CREATE TABLE Sluzba
(
	Nazev VARCHAR(50) NOT NULL,
	OdhadovanaDobaProvedeni VARCHAR(50) NULL,
	PribliznaCena DOUBLE PRECISION NULL,
	SluzbaID INT NOT NULL GENERATED ALWAYS AS IDENTITY,
	RezervaceID INT NOT NULL,
	CONSTRAINT PK_Sluzba PRIMARY KEY (SluzbaID)
);

CREATE TABLE Vozidlo
(
	Model VARCHAR(100) NOT NULL,
	Spz VARCHAR(8) NOT NULL,
	VozidloID INT NOT NULL GENERATED ALWAYS AS IDENTITY,
	ZakaznikID INT NOT NULL,
	CONSTRAINT PK_Vozidlo PRIMARY KEY (VozidloID)
);

CREATE TABLE Zakaznik
(
	ZakaznikID INT NOT NULL GENERATED ALWAYS AS IDENTITY,
	CONSTRAINT PK_Zakaznik PRIMARY KEY (ZakaznikID)
);


ALTER TABLE Administrator 
 ADD CONSTRAINT FK_Administrator_Role
	FOREIGN KEY (AdministratorID) REFERENCES Role (RoleID) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Mechanik 
 ADD CONSTRAINT FK_Mechanik_Role
	FOREIGN KEY (MechanikID) REFERENCES Role (RoleID) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Rezervace 
 ADD CONSTRAINT FK_Rezervace_pridelena
	FOREIGN KEY (MechanikID) REFERENCES Mechanik (MechanikID) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Rezervace 
 ADD CONSTRAINT FK_Rezervace_soucasti
	FOREIGN KEY (VozidloID) REFERENCES Vozidlo (VozidloID) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Role 
 ADD CONSTRAINT FK_Role_Osoba
	FOREIGN KEY (OsobaID) REFERENCES Osoba (OsobaID) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Sluzba 
 ADD CONSTRAINT FK_Sluzba_bude
	FOREIGN KEY (RezervaceID) REFERENCES Rezervace (RezervaceID) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Vozidlo 
 ADD CONSTRAINT FK_Vozidlo_je
	FOREIGN KEY (ZakaznikID) REFERENCES Zakaznik (ZakaznikID) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Zakaznik 
 ADD CONSTRAINT FK_Zakaznik_Role
	FOREIGN KEY (ZakaznikID) REFERENCES Role (RoleID) ON DELETE No Action ON UPDATE No Action
;